name       : colord-gtk
version    : 0.3.0
release    : 1
source     :
    - https://www.freedesktop.org/software/colord/releases/colord-gtk-0.3.0.tar.xz : b9466656d66d9a6ffbc2dd04fa91c8f6af516bf9efaacb69744eec0f56f3c1d0
license    : LGPL-3.0-only
component  : desktop.core
summary    : Additional GTK support code for colord.
description: |
    Additional GTK support code for colord.
builddeps  :
    - pkgconfig(colorhug)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(lcms2)
    - vala
setup      : |
    %meson_configure -Ddocs=false -Dman=false
build      : |
    %ninja_build
install    : |
    %ninja_install
